### PR TITLE
Scrolling commands, html padding fix

### PR DESCRIPTION
**Pull request by alexwalling**
Just added in CSS to enable scrolling through the vimrc commands as opposed to scrolling the entire webpage.
Fixed padding-bottom so there is no scrolling of the page. It is now one single webpage.

### CODE REVIEW

**Comment by dawsonbotsford** [comment]
The left side scrolling is nice, but the vertical size is far too small. The css can be modified such that the left side is still the same height as the right, thus users can see more options at once. In my browser the left side is about half the height of the right side code editor.

I'll change this and push tomorrow if you don't want to give it a fix in the meantime.

Thanks for contributing!

**Comment by alexwalling** [comment]
I put the wrong value in for the hight. It was supposed to be 460 to match the code(Did it in my browser to test but forgot to change the code to match) will do another pull request

**Comment by dawsonbotsford** [comment]
Pull requests auto update when you push to your fork, no need!

On Sunday, February 7, 2016, Alex Walling <notifications@github.com> wrote:

> I put the wrong value in for the hight. It was supposed to be 460 to match
> the code(Did it in my browser to test but forgot to change the code to
> match) will do another pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dawsonbotsford/vimrcBuilder/pull/14#issuecomment-181133266>
> .
>


-- 
Dawson Botsford

<http://hackcu.org/>

Dawson Botsford / Director of Operations
dawsonbotsford@gmail.com / 865-804-9305


HackCU.org <http://hackcu.org/>

[image: LinkedIn]
<https://www.linkedin.com/profile/view?id=354626699&trk=nav_responsive_tab_profile_pic>
 [image: Github] <http://github.com/dawsonbotsford> [image: Twitter]
<http://twitter.com/dawsonbotsford>

**Comment by alexwalling** [comment]
I figured that out! That's awesome. Anyways it's fixed! let me know what you think

**Comment by dawsonbotsford** [comment]
About to merge and then I realized it is not very user friendly on the left side to have no scroll bar until you begin scrolling. It would be so useful for people without a scroll-wheel or a mac, because there is no clear UI trend we are conforming to which shows them the left side is scrollable.

Do you want to poke around for a solution to that? I couldn't find anything off the bat

**Comment by alexwalling** [comment]
That makes sense! I'm gonna look around for a solution to it

**Comment by alexwalling** [comment]
I checked it out on my desktop and it always give the scrollbar visual cue.  I was doing some reading and it seems to be a mac thing that removes the visual side scroll bar.

**Comment by alexwalling** [comment]
It did bring up a problem with my css that it looked funny only changing based on the pixels as opposed to filling the whole screen so I just added a fix to that as well.

**Comment by dawsonbotsford** [comment]
Sweet all done and pushed live!

**Pull request merged**
